button:
  -
    name: "开始制作"
    sub_button:
      -
        type: "pic_weixin"
        name: "上传图片"
        key: 'SEND_PIC'
  -
    type: "click"
    name: "我的海报"
    key: "MY_HAIBAO"
  -
    name: "更多"
    sub_button:
      -
        type: "view"
        name: "常见问题"
        url: 'http://mp.weixinmomo.com/pages/faq'
      -
        type: "view"
        name: "反馈与建议"
        url: 'http://mp.weixinmomo.com/pages/advise'
      -
        type: "view"
        name: "关于我们"
        url: 'http://mp.weixinmomo.com/pages/about'
