button:
  -
    type: "pic_weixin"
    name: "上传图片"
    key: 'SEND_PIC'
  -
    type: "view"
    name: "我的海报"
    # 需修改回调网址
    url: 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxb4d6379ea2e8b4b5&redirect_uri=http%3a%2f%2fwww.getxrp.com%2fwechats_redirect&response_type=code&scope=snsapi_base&state=123#wechat_redirect'
  -
    name: "更多"
    sub_button:
      -
        type: "view"
        name: "常见问题"
        url: 'http://mp.weixinmomo.com/pages/faq'
      -
        type: "view"
        name: "反馈与建议"
        url: 'http://mp.weixinmomo.com/pages/advise'
      -
        type: "view"
        name: "关于我们"
        url: 'http://mp.weixinmomo.com/pages/about'
