button:
  -
    name: "开始制作"
    sub_button:
      -
        type: "pic_weixin"
        name: "上传图片"
        key: 'SEND_PIC'
  -
    type: "click"
    name: "我的海报"
    key: "MY_HAIBAO"
  -
    name: "更多"
    sub_button:
      -
        type: "view"
        name: "常见问题"
        url: 'http://mp.weixinmomo.com/pages/faq'
      -
        type: "view"
        name: "反馈与建议"
        url: 'http://mp.weixinmomo.com/pages/advise'
      -
        type: "view"
        name: "关于我们"
        url: 'http://mp.weixinmomo.com/pages/about'
      -
        type: "view"
        name: "网页授权获取用户基本信息"
        # 需修改回调网址
        url: 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxb4d6379ea2e8b4b5&redirect_uri=http%3a%2f%2fwww.getxrp.com%2fwechat&response_type=code&scope=snsapi_base&state=123#wechat_redirect'
